apiVersion: v1
kind: Namespace
metadata:
  name: exam-0-task-05
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-demo
  namespace: exam-0-task-05
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: app
        image: nginx:1.21
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"