apiVersion: v1
kind: ConfigMap
metadata:
  name: advanced-config
  namespace: exam-1-task-11
data:
  setting: "advanced"
  debug: "enabled"
  timeout: "30"
  internal: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-advanced-demo
  namespace: exam-1-task-11
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo 'setting='$(cat /config/setting) && sleep 3600"]
      volumeMounts:
        - name: config
          mountPath: /config/setting
          subPath: setting
  volumes:
    - name: config
      configMap:
        name: advanced-config