apiVersion: v1
kind: ConfigMap
metadata:
  name: advanced-config
  namespace: exam-1-task-11
data:
  app.conf: "setting=advanced"
  unused.txt: "should-not-be-mounted"
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-advanced-demo
  namespace: exam-1-task-11
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "cat /etc/app/app.conf && sleep 3600"]
      volumeMounts:
        - name: config
          mountPath: /etc/app/app.conf
          subPath: app.conf
  volumes:
    - name: config
      configMap:
        name: advanced-config