apiVersion: v1
kind: Pod
metadata:
  name: logger-demo
  namespace: exam-1-task-09
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo 'INFO: Application started'; echo 'ERROR: Failed to connect to database'; echo 'INFO: Retrying...'; sleep 3600"]