apiVersion: v1
kind: Pod
metadata:
  name: custom-image-demo
  namespace: exam-0-task-13
spec:
  containers:
  - name: custom-app
    image: custom-image:latest
    imagePullPolicy: Never
    command: ["sh", "-c", "cat /app/message.txt && sleep 3600"]
