apiVersion: v1
kind: Namespace
metadata:
  name: exam-0-task-08
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
  namespace: exam-0-task-08
spec:
  containers:
    - name: main-app
      image: busybox
      command: ["sh", "-c", "echo Hello from main-app > /shared/message && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared
    - name: sidecar
      image: busybox
      command: ["sh", "-c", "sleep 5 && cat /shared/message && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared
  volumes:
    - name: shared-data
      emptyDir: {}
