apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: messages.exam.local
spec:
  group: exam.local
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                text:
                  type: string
  scope: Namespaced
  names:
    plural: messages
    singular: message
    kind: Message
    shortNames:
      - msg
---
apiVersion: exam.local/v1
kind: Message
metadata:
  name: hello-msg
  namespace: exam-1-task-10
spec:
  text: "Hello CRD!"