apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: exam-0-task-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
