apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exam-0-task-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:1.21
        ports:
        - containerPort: 80
