apiVersion: apps/v1
kind: Deployment
metadata:
  name: unrelated
  namespace: exam-0-task-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unrelated
  template:
    metadata:
      labels:
        app: unrelated
    spec:
      containers:
      - name: unrelated
        image: nginx:1.21
        ports:
        - containerPort: 80
