apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: ns-a
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: ns-b
  labels:
    app: client
spec:
  containers:
    - name: client
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ns-a
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ns-b
  namespace: ns-a
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ns-b
      ports:
        - protocol: TCP
          port: 80