apiVersion: v1
kind: Namespace
metadata:
  name: exam-0-task-09
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-deployment
  namespace: exam-0-task-09
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-deployment
  template:
    metadata:
      labels:
        app: broken-deployment
    spec:
      containers:
      - name: broken-container
        image: nginx:1.21
        ports:
        - containerPort: 80
