apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-deployment
  namespace: exam-0-task-09
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken
  template:
    metadata:
      labels:
        app: broken
    spec:
      containers:
      - name: broken-container
        image: nginx:doesnotexist
        ports:
        - containerPort: 80
