apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-deployment
  namespace: exam-0-task-09
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: broken-container
        image: nginx:1.20.118-pre
        ports:
        - containerPort: 80
