apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-app
  namespace: exam-1-task-07
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ha-app
  template:
    metadata:
      labels:
        app: ha-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ha-pdb
  namespace: exam-1-task-07
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ha-app