apiVersion: v1
kind: Pod
metadata:
  name: broken-app
  namespace: exam-1-task-09
spec:
  containers:
    - name: web-server
      image: nginx:1.21
      ports:
        - containerPort: 80
      command: ["sh", "-c", "echo 'Starting nginx on port 8080'; nginx -g 'daemon off;' -c /etc/nginx/nginx.conf"]
      volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: config
      configMap:
        name: nginx-config