apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: exam-1-task-09
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 8080;
            location / {
                root /usr/share/nginx/html;
                index index.html;
                directive "absolute";
            }
        }
    }