apiVersion: v1
kind: Namespace
metadata:
  name: exam-0-task-03
---
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
  namespace: exam-0-task-03
type: Opaque
data:
  SECRET_MESSAGE: VG9wU2VjcmV0VmFsdWU=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-demo
  namespace: exam-0-task-03
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo $SECRET_MESSAGE
      sleep 3600
    env:
    - name: SECRET_MESSAGE
      valueFrom:
        secretKeyRef:
          name: env-secret
          key: SECRET_MESSAGE