apiVersion: v1
kind: Namespace
metadata:
  name: exam-0-task-03
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: exam-0-task-03
type: Opaque
data:
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
  namespace: exam-0-task-03
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo $DB_PASSWORD
      sleep 3600
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_PASSWORD