apiVersion: v1
kind: Secret
metadata:
  name: advanced-secret
  namespace: exam-1-task-12
type: Opaque
data:
  encoded-data: U1VDQ0VTU0ZVTCE=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-advanced-demo
  namespace: exam-1-task-12
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo $DECODED_MESSAGE && sleep 3600"]
      env:
        - name: DECODED_MESSAGE
          valueFrom:
            secretKeyRef:
              name: advanced-secret
              key: encoded-data