apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: exam-1-task-08
spec:
  initContainers:
    - name: init
      image: busybox
      command: ["sh", "-c", "echo init ready > /data/status.txt"]
      volumeMounts:
        - name: data
          mountPath: /data
  containers:
    - name: main
      image: busybox
      command: ["sh", "-c", "cat /data/status.txt && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      emptyDir: {}