apiVersion: v1
kind: PersistentVolume
metadata:
  name: exam1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/exam1-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exam1-pvc
  namespace: exam-1-task-03
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-demo
  namespace: exam-1-task-03
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo persistent test > /data/test.txt && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: exam1-pvc