apiVersion: v1
kind: Namespace
metadata:
  name: exam-0-task-07
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: exam-0-task-07
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
      - name: web
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: exam-0-task-07
spec:
  selector:
    app: web-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
