
apiVersion: v1
kind: Pod
metadata:
  name: ambassador-demo
  namespace: exam-1-task-13
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3 && wget -S -O- --timeout=5 http://localhost:8080 2>&1 || true; sleep 3600"]
    - name: proxy
      image: nginx:alpine
      command: ["sh", "-c", "nginx -g 'daemon off;'"]
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-proxy-config