apiVersion: v1
kind: Pod
metadata:
  name: ambassador-demo
  namespace: exam-1-task-13
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "wget -qO- --timeout=5 http://localhost:8080 || true; sleep 3600"]
    - name: ambassador
      image: busybox
      command: ["sh", "-c", "apk add --no-cache socat && socat TCP-LISTEN:8080,fork TCP:example.com:80"]