apiVersion: v1
kind: Namespace
metadata:
  name: exam-0-task-02
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-config
  namespace: exam-0-task-02
data:
  config.txt: "This is from ConfigMap volume!"
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-demo
  namespace: exam-0-task-02
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      cat /etc/config/config.txt
      sleep 3600
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: volume-config