apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: exam-0-task-12
subjects:
  - kind: ServiceAccount
    name: limited-access
    namespace: exam-0-task-12
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
