apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: exam-1-task-05
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 256Mi
    limits.cpu: "500m"
    limits.memory: 256Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: exam-1-task-05
spec:
  limits:
    - default:
        cpu: 200m
        memory: 128Mi
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: quota-demo
  namespace: exam-1-task-05
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]